#!/usr/bin/env bash
repeat () {
	if [ $2 -ge 1 ]; then seq -f "$1" -s '' $2; fi
}

print_progress () {
	passed=$1
	total=$2
	remM=$(( (total-passed) / 60 ));
	remS=$(( (total - remM*60) - passed ));
	progress=$(( passed * 50 / total ));
	echo -ne '  progress: [';
	repeat "#" $progress;
	repeat " " $((50-progress));
	echo -ne '] T-'$remM':'`printf "%02d" $remS`'\r';
}

parsedtime=`echo "$1" | awk '{split($0,a,":"); print a[1],a[2],0}'`
minutes=$(echo $parsedtime | cut -f1 -d\ )
seconds=$(echo $parsedtime | cut -f2 -d\ )
seconds=$((minutes*60+seconds))

for ((t=0;t<seconds;++t)) do
	print_progress $t $seconds
	sleep 1;
	print_progress $((t+1)) $seconds
done
echo
say напоминание, чай заварился. && tput bel
echo -e "🍵"
