#!/usr/bin/env bash
repeat () {
	if [ $2 -ge 1 ]; then seq -f "$1" -s '' $2; fi
}

minutes="$1"
seconds=$((minutes*60))
for ((t=0;t<seconds;++t)) do
	remM=$(( (seconds-t) / 60 ));
	remS=$(( (seconds - remM*60) - t ));
	progress=$(( (t+1) * 50 / seconds ));
	echo -ne '  progress: [';
	repeat "#" $progress;
	repeat " " $((50-progress));
	echo -ne '] T-'$remM':'`printf "%02d" $remS`'\r';
	sleep 1;
done
echo
say напоминание, чай заварился. && tput bel
